import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../../core/services/api.service';
@Component({ template:`<div class="page-wrap"><div class="page-header"><h1>📝 Driver Coaching Log</h1><button class="btn-primary" (click)="showForm=!showForm">+ New Session</button></div><div class="form-card" *ngIf="showForm"><h3>Log Coaching Session</h3><div class="form-grid"><div class="field"><label>Driver</label><select [(ngModel)]="entry.driver_id"><option *ngFor="let d of drivers" [value]="d.id">{{d.name}}</option></select></div><div class="field"><label>Date</label><input type="date" [(ngModel)]="entry.date"></div><div class="field"><label>Category</label><select [(ngModel)]="entry.category"><option>Safety</option><option>Performance</option><option>Attendance</option><option>Positive Recognition</option><option>Corrective Action</option></select></div></div><div class="field full"><label>Notes</label><textarea [(ngModel)]="entry.notes" rows="4"></textarea></div><div class="form-actions"><button class="btn-secondary" (click)="showForm=false">Cancel</button><button class="btn-primary" (click)="save()">Save</button></div></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Driver</th><th>Category</th><th>Notes</th><th>Manager</th></tr></thead><tbody><tr *ngFor="let e of entries"><td>{{e.date|date:'MM/dd/yy'}}</td><td>{{e.driver_name}}</td><td><span class="pill" [class]="e.category.toLowerCase().replace(' ','-')">{{e.category}}</span></td><td>{{e.notes}}</td><td>{{e.manager_name}}</td></tr></tbody></table></div></div>`, styleUrls:['../roster/driver-roster.component.scss'] })
export class CoachingLogComponent implements OnInit {
  entries: any[] = []; drivers: any[] = []; showForm = false;
  entry = { driver_id:null, date:'', category:'Safety', notes:'' };
  constructor(private api: ApiService) {}
  ngOnInit() { this.api.getPaged<any>('coaching-sessions').subscribe(r=>{ if(r.success&&r.data) this.entries=r.data.data; }); this.api.getPaged<any>('drivers').subscribe(r=>{ if(r.success&&r.data) this.drivers=r.data.data; }); }
  save() { this.api.post('coaching-sessions',this.entry).subscribe(r=>{ if(r.success){this.showForm=false;this.ngOnInit();} }); }
}
