import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../../core/services/api.service';
@Component({ template:`<div class="page-wrap"><div class="page-header"><h1>🧪 Drug & Alcohol Testing</h1><button class="btn-primary" (click)="showForm=!showForm">+ Log Test</button></div><div class="form-card" *ngIf="showForm"><h3>Log Test Record — 49 CFR Part 382</h3><div class="form-grid"><div class="field"><label>Driver</label><select [(ngModel)]="entry.driver_id"><option *ngFor="let d of drivers" [value]="d.id">{{d.name}}</option></select></div><div class="field"><label>Test Type</label><select [(ngModel)]="entry.test_type"><option>Pre-Employment</option><option>Random</option><option>Post-Accident</option><option>Reasonable Suspicion</option><option>Return-to-Duty</option><option>Follow-Up</option></select></div><div class="field"><label>Test Date</label><input type="date" [(ngModel)]="entry.test_date"></div><div class="field"><label>Result</label><select [(ngModel)]="entry.result"><option>Negative</option><option>Positive</option><option>Refused</option><option>Cancelled</option></select></div><div class="field"><label>Collection Site</label><input [(ngModel)]="entry.collection_site"></div><div class="field"><label>MRO Name</label><input [(ngModel)]="entry.mro_name"></div></div><div class="form-actions"><button class="btn-secondary" (click)="showForm=false">Cancel</button><button class="btn-primary" (click)="save()">Save Record</button></div></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Driver</th><th>Type</th><th>Result</th><th>Collection Site</th></tr></thead><tbody><tr *ngFor="let t of tests"><td>{{t.test_date|date:'MM/dd/yy'}}</td><td>{{t.driver_name}}</td><td>{{t.test_type}}</td><td><span class="pill" [class]="t.result.toLowerCase()">{{t.result}}</span></td><td>{{t.collection_site}}</td></tr></tbody></table></div></div>`, styleUrls:['../roster/driver-roster.component.scss'] })
export class DrugTestingComponent implements OnInit {
  tests: any[] = []; drivers: any[] = []; showForm = false;
  entry = { driver_id:null, test_type:'Random', test_date:'', result:'Negative', collection_site:'', mro_name:'' };
  constructor(private api: ApiService) {}
  ngOnInit() { this.api.getPaged<any>('drug-tests').subscribe(r=>{ if(r.success&&r.data) this.tests=r.data.data; }); this.api.getPaged<any>('drivers').subscribe(r=>{ if(r.success&&r.data) this.drivers=r.data.data; }); }
  save() { this.api.post('drug-tests',this.entry).subscribe(r=>{ if(r.success){this.showForm=false;this.ngOnInit();} }); }
}
