import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../../core/services/api.service';
import { AuthService } from '../../../core/services/auth.service';
import { Settlement } from '../../../core/models';
@Component({ template:`<div class="page-wrap"><div class="page-header"><h1>💰 My Pay</h1></div><div *ngFor="let s of settlements" class="settlement-card"><div class="week-label">{{s.week_start|date:'MM/dd/yyyy'}} – {{s.week_end|date:'MM/dd/yyyy'}}</div><div class="pay-grid"><div class="pay-row"><span>Gross Revenue</span><span class="green">{{s.gross_revenue|currency}}</span></div><div class="pay-row"><span>Dispatch Fee ({{s.dispatch_pct}}%)</span><span class="red">-{{s.dispatch_fee|currency}}</span></div><div class="pay-row"><span>Fuel Deductions</span><span class="red">-{{s.fuel_deductions|currency}}</span></div><div class="pay-row"><span>Other Deductions</span><span class="red">-{{s.other_deductions|currency}}</span></div><div class="pay-row total"><span>NET PAY</span><span class="green">{{s.net_pay|currency}}</span></div></div><span class="status-pill" [class]="s.status">{{s.status}}</span></div></div>`, styles:[`@import '../../../../shared/styles/page'; .settlement-card{background:#161b22;border:1px solid #30363d;border-radius:12px;padding:20px;margin-bottom:16px;} .week-label{font-weight:700;color:#e6edf3;margin-bottom:12px;font-size:14px;} .pay-grid{display:flex;flex-direction:column;gap:8px;margin-bottom:12px;} .pay-row{display:flex;justify-content:space-between;font-size:13px;color:#8b949e;&.total{border-top:1px solid #30363d;padding-top:8px;font-weight:800;font-size:15px;color:#e6edf3;}} .green{color:#4ade80;} .red{color:#f87171;} .status-pill{padding:3px 10px;border-radius:20px;font-size:11px;font-weight:700;&.approved{background:rgba(22,163,74,.2);color:#4ade80;}&.pending{background:rgba(217,119,6,.2);color:#fbbf24;}&.paid{background:rgba(37,99,235,.2);color:#60a5fa;}}`] })
export class DriverPortalComponent implements OnInit {
  settlements: Settlement[] = [];
  constructor(private api: ApiService, public auth: AuthService) {}
  ngOnInit() { this.api.getPaged<Settlement>('settlements',1,10).subscribe(r=>{ if(r.success && r.data) this.settlements=r.data.data; }); }
}
